# Generated by Django 5.0.4 on 2024-05-23 14:11

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='Image with that Particular field', upload_to=app.models.getFileName),
        ),
    ]
