# Generated by Django 5.0.4 on 2024-05-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
