# Generated by Django 5.0.6 on 2024-10-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin approval status'),
        ),
    ]
