# Generated by Django 5.0.6 on 2024-11-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_review_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='sentiment',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
